### ISSUE TITLE
Missing "libhdmiin.so" file

### ISSUE THREAD

**Issue by habi-kvana** [Amlogic-Lineage/android_vendor_amlogic_common_frameworks#2]
Hi Team,

I am facing an issue while running the app with this code.

Exception is:

java.lang.UnsatisfiedLinkError: dlopen failed: library "libhdmiin.so" not found

How to get this "libhdmiin.so" file and run successfully our app?

If you are missing in uploading, please upload/share it with us, or provide us the steps to generate it.

Kindly help on this to resolve the issue.

Thanks in advance.

**Comment by npjohnson** [comment]
We don't actively support building with any of this, this organization is for staging things.

**Comment by habi-kvana** [comment]
thanks for the reply @npjohnson 
where can i get the answer for this(libhdmiin.so file) and let me know which organizations do the development
